export const PRODUCT_FETCH_SUCCESS = 'PRODUCTTEST/PRODUCT/FETCHSUCCESS';
export const PRODUCT_LIST_SUCCESS = 'PRODUCTTEST/PRODUCT/LISTSUCCESS';
export const PRODUCT_REQUEST = 'PRODUCTTEST/PRODUCT/REQUEST';
export const PRODUCT_ERRROR = 'PRODUCTTEST/PRODUCT/ERROR';